config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create]

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, length: { minimum: 2 }
    validates :last_name, length: { minimum: 2 }
    validates :job, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      flash[:alert] = "We are processing your registration."
      ProcessUserJob.perform_later(user_params)
      redirect_to users_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :last_name, :job, :remote_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Job Seeker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container-fluid">
    <!-- Flash Notice -->
    <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>

    <div class="row">
      <div class="col-md-6 text-center text-md-left pr-md-5">
        <h1 class="display-4 title">Estudar Async</h1>
        <p class="lead">This is an application that 
          demonstrates how to integrate the Rails 
          backend with an external service using Interactors 
          to encapsulate programming logic and asynchronous 
        programming with the help of Sidekiq.</p>
      </div>
      <div class="col-1 offset-md-4">
        <%= image_tag("estudar.png", :alt => "Fundação Estudar") %>
      </div>
    </div>

    <br>
    <br>
    <%= yield %>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= form_with(model: user, local: true) do |form| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %>
    
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, class:"form-control" %>
          </div>
        </div>      
      </div>
      <div class="col-4">
        <div class="form-group">
          <div class="field">
            <%= form.label :last_name %>
            <%= form.text_field :last_name, class:"form-control" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          <div class="field">
            <%= form.label :job %>
            <%= form.text_field :job, class:"form-control" %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex">
      <div class="ml-auto p-2">
        <div class="actions">
          <%= link_to 'Back', users_path, class:"btn btn-light" %>
          <%= form.submit 'Create user', :class => 'btn btn-success'  %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="center">
  <table class="table text-center">
    <thead>
      <tr>
        <th>Name</th>
        <th>Last Name</th>
        <th>Job</th>
        <th>Remote Id</th>
      </tr>
    </thead>

    <tbody>
      <% if @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.job %></td>
        <td><%= user.remote_id %></td>
      </tr>
      <% end.empty? %>
      <td colspan="4">No users registered</td>
      <% end %>
    </tbody>
  </table>
  <br> 
</div>


<div class="d-flex">
  <div class="ml-auto p-2">
    <%= link_to 'New User', new_user_path, class:"btn btn-success" %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>